// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu6C26kMezLWx_z1fvaR6GFlrcvWee-3s',
    appId: '1:910989196533:web:1b1e68105e5b8b92c2d9bc',
    messagingSenderId: '910989196533',
    projectId: 'e-commerce-fe508',
    authDomain: 'e-commerce-fe508.firebaseapp.com',
    storageBucket: 'e-commerce-fe508.appspot.com',
    measurementId: 'G-LGNF9SSM44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr19yI_XfkkpkrTy0zkoakmwz76ILMZu8',
    appId: '1:910989196533:android:9da5e692a2a6e0e6c2d9bc',
    messagingSenderId: '910989196533',
    projectId: 'e-commerce-fe508',
    storageBucket: 'e-commerce-fe508.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwrF7MBvQ7zChVPqx3e1WSS1J5Eq87a3k',
    appId: '1:910989196533:ios:2d6a985fa75c61b3c2d9bc',
    messagingSenderId: '910989196533',
    projectId: 'e-commerce-fe508',
    storageBucket: 'e-commerce-fe508.appspot.com',
    iosClientId: '910989196533-lrhbv102m853veu1g483qlth4cg00s2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );
}
